### PR TITLE
Upgrade to v2.0 OAuth endpoint

### PR DESCRIPTION
**Pull request by joelvh**
Also fixes the module name in the version file and uses the UPN as email as fall-back

### CODE REVIEW

**Comment by synth** [comment]
@joelvh hey - sorry for the delay, didn't see this until now. This looks solid, but I don't have the time to test it atm. Also due to the nature of the changes, I think we should do a full feature bump so bug fixes could still be applied to the v1 line. Now that I see other people are using this gem, I'll try to put some time into again.

**Comment by joelvh** [comment]
@synth no problem. Let me know when you get a chance to review or need a hand with anything. Thanks.

**Comment by cyclotron3k** [comment]
Is this going to be released any time soon? Would be super cool if I could include a gem instead of hotlinking the fork by @cbales

**Comment by cyclotron3k** [comment]
Would be great to get this merged and released

**Comment by synth** [comment]
@cyclotron3k there ya go!

**Comment by cyclotron3k** [comment]
Awesome! Thanks @synth and @joelvh!

Will you be bumping the version and publishing the gem to ruby gems?

Thanks

**Pull request merged**
